name: test_cpp_build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: env
        run: g++ main.cpp

      - name: ls
        run: ls
        
      - name: bot
        run: curl https://api.telegram.org/bot<token>/getUpdates

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: "a.out"
          retention-days: 1
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_DEBUG }}
          token: ${{ secrets.TELEGRAM_TOKEN_DEBUG }}
          message: i'm sexy and i know it
          document: a.out
